$(function(){
 $('#red').click(function(){
     $('.box').css('background-color','#FF0000');
 });
 $('#green').click(function(){
     $('.box').css('background-color','#008000');
 });
 $('#blue').click(function(){
     $('.box').css('background-color','#0000FF');
 });
 $('#reset').click(function(){
     $('.box').css('background-color','#000');
 });
});